{{- if .Values.secrets.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-release-notifier.fullname" . }}-github-token
  labels:
    {{- include "github-release-notifier.labels" . | nindent 4 }}
type: Opaque
data:
  github_token: {{ .Values.secrets.githubToken | b64enc }}
{{- end }}
